pipeline {
    agent any
    tools { 
        maven 'maven' 
        jdk 'java1.8' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('scm') {
            steps {
                git credentialsId: 'ef9198fe-193d-4977-ab29-e622c949f981', url: 'https://github.com/ranand219/project1.git'
            }
        }
        
        stage ('build') {
            steps {
                sh 'mvn clean install'
            }
		}
    }
}
