pipeline {
    agent any
    tools { 
        maven 'maven' 
        jdk 'jdk' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('scm') {
            steps {
                git credentialsId: 'c6a8f42d-7acd-470e-86cf-bf9eaffc6dd2', url: 'https://github.com/ranand219/project1.git'
            }
        }
        
        stage ('build') {
            steps {
                sh 'mvn clean install'
            }
		}
    }
}
